### ISSUE TITLE
Error: Zend_Db_Statement_Mysqli_Exception Mysqli prepare error: Table 'lincolnh_omek1.omek_neatline_simile_exhibit_expansions' doesn't exist

### ISSUE THREAD

**Issue by sheltongd** [scholarslab/nl-widget-Simile#12]
Hello, I am attempting to use the Neatline, NeatlineTime, and the Simile widget to create a timeline for an Omeka site. However, once Simile is active on the site Neatline malfunctions, giving this error: tion 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: Table 'lincolnh_omek1.omek_neatline_simile_exhibit_expansions' doesn't exist' in /home/lincolnh/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /home/lincolnh/public_html/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `neatlin...')
#1 /home/lincolnh/public_html/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `neatlin...')
#2 /home/lincolnh/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT `neatlin...')
#3 [internal function]: Zend_Db_Adapter_Abstract->query(Object(Omeka_Db_Select), Array)
#4 /home/lincolnh/public_html/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#5 /home/lincolnh/public_html/application/libraries/Omeka/Db/Table.php(648): Omeka_Db->__call('query', Array)
#6 /home/lincolnh/public_html/application/libraries/Omeka/Db/Table.php(648): Omeka_Db->query(Object(Omeka_Db_Select), Array)
#7 /home/lincolnh/public_html/application/libraries/Omeka/Db/Table.php(281): Omeka_Db_Table->fetchObjects(Object(Omeka_Db_Select))
#8 [internal function]: Omeka_Db_Table->findBy(Array, 10, 1)
#9 /home/lincolnh/public_html/application/controllers/helpers/Db.php(59): call_user_func_array(Array, Array)
#10 /home/lincolnh/public_html/application/libraries/Omeka/Controller/AbstractActionController.php(128): Omeka_Controller_Action_Helper_Db->__call('findBy', Array)
#11 /home/lincolnh/public_html/application/libraries/Omeka/Controller/AbstractActionController.php(128): Omeka_Controller_Action_Helper_Db->findBy(Array, 10, 1)
#12 /home/lincolnh/public_html/plugins/Neatline/controllers/ExhibitsController.php(79): Omeka_Controller_AbstractActionController->browseAction()
#13 /home/lincolnh/public_html/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->browseAction()
#14 /home/lincolnh/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('browseAction')
#15 /home/lincolnh/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#16 /home/lincolnh/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#17 /home/lincolnh/public_html/application/libraries/Zend/Application.php(382): Zend_Application_Bootstrap_Bootstrap->run()
#18 /home/lincolnh/public_html/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#19 /home/lincolnh/public_html/admin/index.php(28): Omeka_Application->run()
#20 {main}

Is there a solution to this issue?

**Comment by erochest** [comment]
Hi @sheltongd ,

A little more information would be helpful for digging into this. What versions of Omeka, Neatline, and Neatline SIMILE are you using? Also what are you doing just before this error is thrown?

Thanks

**Comment by sheltongd** [comment]
Thanks,

So Omeka is version 2.3.1, Neatline is version 2.51,Neatline time is 2.1, and SIMILE Timeline is 2.0.4. When the error is shown, Neatline Simile has been installed (and all three are installed) and we attempt to use Neatline we get the error I showed above.
